CXX := g++
CXX_FLAGS := -I./deps/include -I./deps/include/v8 -std=c++11
V8_ARCHIVES = \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/Console.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/Debugger.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/HeapProfiler.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/injected-script.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/inspected-context.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/Profiler.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/Protocol.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/remote-object-id.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/Runtime.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/Schema.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/search-util.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/string-16.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/string-util.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/test-interface.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/v8-console-agent-impl.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/v8-console-message.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/v8-console.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/v8-debugger-agent-impl.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/v8-debugger-script.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/v8-debugger.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/v8-function-call.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/v8-heap-profiler-agent-impl.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/v8-injected-script-host.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/v8-inspector-impl.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/v8-inspector-session-impl.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/v8-internal-value-type.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/v8-profiler-agent-impl.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/v8-regex.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/v8-runtime-agent-impl.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/v8-schema-agent-impl.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/v8-stack-trace-impl.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/v8-value-utils.o \
	deps/v8/out.gn/x64.release/obj/src/inspector/inspector/wasm-translation.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/affixpatternparser.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/alphaindex.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/anytrans.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/astro.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/basictz.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/bocsu.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/brktrans.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/buddhcal.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/calendar.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/casetrn.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/cecal.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/chnsecal.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/choicfmt.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/coleitr.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/coll.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/collation.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/collationbuilder.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/collationcompare.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/collationdata.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/collationdatabuilder.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/collationdatareader.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/collationdatawriter.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/collationfastlatin.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/collationfastlatinbuilder.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/collationfcd.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/collationiterator.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/collationkeys.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/collationroot.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/collationrootelements.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/collationruleparser.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/collationsets.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/collationsettings.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/collationtailoring.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/collationweights.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/compactdecimalformat.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/coptccal.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/cpdtrans.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/csdetect.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/csmatch.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/csr2022.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/csrecog.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/csrmbcs.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/csrsbcs.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/csrucode.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/csrutf8.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/curramt.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/currfmt.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/currpinf.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/currunit.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/dangical.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/datefmt.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/dayperiodrules.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/dcfmtsym.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/decContext.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/decfmtst.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/decimalformatpattern.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/decimfmt.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/decimfmtimpl.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/decNumber.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/digitaffix.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/digitaffixesandpadding.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/digitformatter.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/digitgrouping.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/digitinterval.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/digitlst.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/dtfmtsym.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/dtitvfmt.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/dtitvinf.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/dtptngen.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/dtrule.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/esctrn.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/ethpccal.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/fmtable.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/fmtable_cnv.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/format.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/fphdlimp.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/fpositer.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/funcrepl.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/gender.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/gregocal.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/gregoimp.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/hebrwcal.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/indiancal.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/inputext.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/islamcal.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/japancal.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/measfmt.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/measunit.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/measure.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/msgfmt.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/name2uni.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/nfrs.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/nfrule.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/nfsubs.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/nortrans.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/nounit.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/nultrans.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/number_affixutils.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/number_compact.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/number_decimalquantity.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/number_decimfmtprops.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/number_fluent.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/number_formatimpl.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/number_grouping.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/number_integerwidth.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/number_longnames.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/number_modifiers.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/number_notation.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/number_padding.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/number_patternmodifier.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/number_patternstring.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/number_rounding.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/number_scientific.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/number_stringbuilder.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/numfmt.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/numsys.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/olsontz.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/persncal.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/pluralaffix.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/plurfmt.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/plurrule.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/precision.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/quant.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/quantityformatter.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/rbnf.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/rbt.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/rbt_data.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/rbt_pars.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/rbt_rule.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/rbt_set.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/rbtz.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/regexcmp.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/regeximp.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/regexst.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/regextxt.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/region.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/reldatefmt.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/reldtfmt.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/rematch.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/remtrans.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/repattrn.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/rulebasedcollator.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/scientificnumberformatter.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/scriptset.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/search.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/selfmt.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/sharedbreakiterator.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/simpletz.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/smallintformatter.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/smpdtfmt.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/smpdtfst.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/sortkey.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/standardplural.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/strmatch.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/strrepl.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/stsearch.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/taiwncal.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/timezone.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/titletrn.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/tmunit.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/tmutamt.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/tmutfmt.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/tolowtrn.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/toupptrn.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/translit.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/transreg.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/tridpars.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/tzfmt.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/tzgnames.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/tznames.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/tznames_impl.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/tzrule.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/tztrans.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/ucal.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/ucln_in.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/ucol.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/ucol_res.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/ucol_sit.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/ucoleitr.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/ucsdet.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/udat.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/udateintervalformat.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/udatpg.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/ufieldpositer.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/uitercollationiterator.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/ulocdata.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/umsg.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/unesctrn.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/uni2name.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/unum.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/unumsys.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/upluralrules.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/uregex.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/uregexc.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/uregion.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/usearch.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/uspoof.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/uspoof_build.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/uspoof_conf.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/uspoof_impl.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/utf16collationiterator.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/utf8collationiterator.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/utmscale.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/utrans.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/valueformatter.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/visibledigits.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/vtzone.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/vzone.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/windtfmt.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/winnmfmt.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/wintzimpl.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/zonemeta.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/zrule.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icui18n/ztrans.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/appendable.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/bmpset.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/brkeng.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/brkiter.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/bytesinkutil.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/bytestream.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/bytestrie.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/bytestriebuilder.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/bytestrieiterator.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/caniter.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/chariter.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/charstr.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/cmemory.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/cstr.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/cstring.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/cwchar.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/dictbe.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/dictionarydata.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/dtintrv.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/edits.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/errorcode.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/filteredbrk.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/filterednormalizer2.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/icudataver.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/icuplug.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/listformatter.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/loadednormalizer2impl.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/locavailable.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/locbased.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/locdispnames.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/locdspnm.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/locid.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/loclikely.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/locmap.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/locresdata.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/locutil.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/messagepattern.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/normalizer2.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/normalizer2impl.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/normlzr.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/parsepos.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/patternprops.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/pluralmap.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/propname.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/propsvec.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/punycode.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/putil.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/rbbi.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/rbbi_cache.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/rbbidata.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/rbbinode.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/rbbirb.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/rbbiscan.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/rbbisetb.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/rbbistbl.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/rbbitblb.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/resbund.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/resbund_cnv.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/resource.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ruleiter.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/schriter.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/serv.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/servlk.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/servlkf.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/servls.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/servnotf.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/servrbf.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/servslkf.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/sharedobject.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/simpleformatter.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/stringpiece.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/stringtriebuilder.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/stubdata.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/uarrsort.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ubidi.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ubidi_props.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ubidiln.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ubiditransform.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ubidiwrt.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ubrk.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucase.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucasemap.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucasemap_titlecase_brkiter.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucat.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/uchar.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucharstrie.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucharstriebuilder.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucharstrieiterator.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/uchriter.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucln_cmn.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucmndata.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucnv.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucnv2022.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucnv_bld.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucnv_cb.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucnv_cnv.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucnv_ct.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucnv_err.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucnv_ext.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucnv_io.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucnv_lmb.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucnv_set.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucnv_u16.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucnv_u32.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucnv_u7.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucnv_u8.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucnvbocu.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucnvdisp.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucnvhz.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucnvisci.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucnvlat1.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucnvmbcs.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucnvscsu.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucnvsel.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucol_swp.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ucurr.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/udata.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/udatamem.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/udataswp.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/uenum.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/uhash.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/uhash_us.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/uidna.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/uinit.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/uinvchar.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/uiter.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ulist.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ulistformatter.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/uloc.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/uloc_keytype.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/uloc_tag.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/umapfile.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/umath.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/umutex.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/unames.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/unifiedcache.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/unifilt.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/unifunct.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/uniset.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/uniset_closure.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/uniset_props.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/unisetspan.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/unistr.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/unistr_case.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/unistr_case_locale.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/unistr_cnv.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/unistr_props.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/unistr_titlecase_brkiter.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/unorm.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/unormcmp.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/uobject.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/uprops.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ures_cnv.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/uresbund.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/uresdata.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/usc_impl.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/uscript.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/uscript_props.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/uset.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/uset_props.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/usetiter.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ushape.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/usprep.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ustack.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ustr_cnv.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ustr_titlecase_brkiter.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ustr_wcs.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ustrcase.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ustrcase_locale.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ustrenum.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ustrfmt.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ustring.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/ustrtrns.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/utext.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/utf_impl.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/util.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/util_props.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/utrace.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/utrie.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/utrie2.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/utrie2_builder.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/uts46.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/utypes.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/uvector.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/uvectr32.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/uvectr64.o \
	deps/v8/out.gn/x64.release/obj/third_party/icu/icuuc/wintz.o \
	deps/v8/out.gn/x64.release/obj/v8_base/access-builder.o \
	deps/v8/out.gn/x64.release/obj/v8_base/access-info.o \
	deps/v8/out.gn/x64.release/obj/v8_base/accessors.o \
	deps/v8/out.gn/x64.release/obj/v8_base/accounting-allocator.o \
	deps/v8/out.gn/x64.release/obj/v8_base/address-map.o \
	deps/v8/out.gn/x64.release/obj/v8_base/all-nodes.o \
	deps/v8/out.gn/x64.release/obj/v8_base/allocation-tracker.o \
	deps/v8/out.gn/x64.release/obj/v8_base/allocation.o \
	deps/v8/out.gn/x64.release/obj/v8_base/api-arguments.o \
	deps/v8/out.gn/x64.release/obj/v8_base/api-natives.o \
	deps/v8/out.gn/x64.release/obj/v8_base/api.o \
	deps/v8/out.gn/x64.release/obj/v8_base/arguments.o \
	deps/v8/out.gn/x64.release/obj/v8_base/array-buffer-collector.o \
	deps/v8/out.gn/x64.release/obj/v8_base/array-buffer-tracker.o \
	deps/v8/out.gn/x64.release/obj/v8_base/asm-js.o \
	deps/v8/out.gn/x64.release/obj/v8_base/asm-parser.o \
	deps/v8/out.gn/x64.release/obj/v8_base/asm-scanner.o \
	deps/v8/out.gn/x64.release/obj/v8_base/asm-types.o \
	deps/v8/out.gn/x64.release/obj/v8_base/assembler-x64.o \
	deps/v8/out.gn/x64.release/obj/v8_base/assembler.o \
	deps/v8/out.gn/x64.release/obj/v8_base/assert-scope.o \
	deps/v8/out.gn/x64.release/obj/v8_base/ast-function-literal-id-reindexer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/ast-value-factory.o \
	deps/v8/out.gn/x64.release/obj/v8_base/ast.o \
	deps/v8/out.gn/x64.release/obj/v8_base/bailout-reason.o \
	deps/v8/out.gn/x64.release/obj/v8_base/basic-block-instrumentor.o \
	deps/v8/out.gn/x64.release/obj/v8_base/basic-block-profiler.o \
	deps/v8/out.gn/x64.release/obj/v8_base/bigint.o \
	deps/v8/out.gn/x64.release/obj/v8_base/bignum-dtoa.o \
	deps/v8/out.gn/x64.release/obj/v8_base/bignum.o \
	deps/v8/out.gn/x64.release/obj/v8_base/bit-vector.o \
	deps/v8/out.gn/x64.release/obj/v8_base/bootstrapper.o \
	deps/v8/out.gn/x64.release/obj/v8_base/branch-elimination.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtin-deserializer-allocator.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtin-deserializer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtin-serializer-allocator.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtin-serializer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtin-snapshot-utils.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtins-api.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtins-array.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtins-arraybuffer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtins-bigint.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtins-boolean.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtins-call.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtins-callsite.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtins-collections.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtins-console.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtins-dataview.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtins-date.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtins-error.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtins-function.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtins-global.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtins-internal.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtins-interpreter.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtins-intl.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtins-json.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtins-math.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtins-number.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtins-object.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtins-promise.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtins-reflect.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtins-regexp.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtins-sharedarraybuffer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtins-string.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtins-symbol.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtins-typedarray.o \
	deps/v8/out.gn/x64.release/obj/v8_base/builtins.o \
	deps/v8/out.gn/x64.release/obj/v8_base/bytecode-analysis.o \
	deps/v8/out.gn/x64.release/obj/v8_base/bytecode-array-accessor.o \
	deps/v8/out.gn/x64.release/obj/v8_base/bytecode-array-builder.o \
	deps/v8/out.gn/x64.release/obj/v8_base/bytecode-array-iterator.o \
	deps/v8/out.gn/x64.release/obj/v8_base/bytecode-array-random-iterator.o \
	deps/v8/out.gn/x64.release/obj/v8_base/bytecode-array-writer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/bytecode-decoder.o \
	deps/v8/out.gn/x64.release/obj/v8_base/bytecode-flags.o \
	deps/v8/out.gn/x64.release/obj/v8_base/bytecode-generator.o \
	deps/v8/out.gn/x64.release/obj/v8_base/bytecode-graph-builder.o \
	deps/v8/out.gn/x64.release/obj/v8_base/bytecode-label.o \
	deps/v8/out.gn/x64.release/obj/v8_base/bytecode-liveness-map.o \
	deps/v8/out.gn/x64.release/obj/v8_base/bytecode-node.o \
	deps/v8/out.gn/x64.release/obj/v8_base/bytecode-operands.o \
	deps/v8/out.gn/x64.release/obj/v8_base/bytecode-register-optimizer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/bytecode-register.o \
	deps/v8/out.gn/x64.release/obj/v8_base/bytecode-source-info.o \
	deps/v8/out.gn/x64.release/obj/v8_base/bytecodes.o \
	deps/v8/out.gn/x64.release/obj/v8_base/c-linkage.o \
	deps/v8/out.gn/x64.release/obj/v8_base/cached-powers.o \
	deps/v8/out.gn/x64.release/obj/v8_base/call-optimization.o \
	deps/v8/out.gn/x64.release/obj/v8_base/cancelable-task.o \
	deps/v8/out.gn/x64.release/obj/v8_base/char-predicates.o \
	deps/v8/out.gn/x64.release/obj/v8_base/checkpoint-elimination.o \
	deps/v8/out.gn/x64.release/obj/v8_base/code-assembler.o \
	deps/v8/out.gn/x64.release/obj/v8_base/code-factory.o \
	deps/v8/out.gn/x64.release/obj/v8_base/code-generator-x64.o \
	deps/v8/out.gn/x64.release/obj/v8_base/code-generator.o \
	deps/v8/out.gn/x64.release/obj/v8_base/code-serializer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/code-stats.o \
	deps/v8/out.gn/x64.release/obj/v8_base/code-stub-assembler.o \
	deps/v8/out.gn/x64.release/obj/v8_base/code-stubs-x64.o \
	deps/v8/out.gn/x64.release/obj/v8_base/code-stubs.o \
	deps/v8/out.gn/x64.release/obj/v8_base/codegen-x64.o \
	deps/v8/out.gn/x64.release/obj/v8_base/codegen.o \
	deps/v8/out.gn/x64.release/obj/v8_base/common-node-cache.o \
	deps/v8/out.gn/x64.release/obj/v8_base/common-operator-reducer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/common-operator.o \
	deps/v8/out.gn/x64.release/obj/v8_base/compilation-cache.o \
	deps/v8/out.gn/x64.release/obj/v8_base/compilation-dependencies.o \
	deps/v8/out.gn/x64.release/obj/v8_base/compilation-info.o \
	deps/v8/out.gn/x64.release/obj/v8_base/compilation-manager.o \
	deps/v8/out.gn/x64.release/obj/v8_base/compilation-statistics.o \
	deps/v8/out.gn/x64.release/obj/v8_base/compile-time-value.o \
	deps/v8/out.gn/x64.release/obj/v8_base/compiler-dispatcher-job.o \
	deps/v8/out.gn/x64.release/obj/v8_base/compiler-dispatcher-tracer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/compiler-dispatcher.o \
	deps/v8/out.gn/x64.release/obj/v8_base/compiler-source-position-table.o \
	deps/v8/out.gn/x64.release/obj/v8_base/compiler.o \
	deps/v8/out.gn/x64.release/obj/v8_base/concurrent-marking.o \
	deps/v8/out.gn/x64.release/obj/v8_base/constant-array-builder.o \
	deps/v8/out.gn/x64.release/obj/v8_base/constants-table-builder.o \
	deps/v8/out.gn/x64.release/obj/v8_base/context-slot-cache.o \
	deps/v8/out.gn/x64.release/obj/v8_base/contexts.o \
	deps/v8/out.gn/x64.release/obj/v8_base/control-equivalence.o \
	deps/v8/out.gn/x64.release/obj/v8_base/control-flow-builders.o \
	deps/v8/out.gn/x64.release/obj/v8_base/control-flow-optimizer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/conversions.o \
	deps/v8/out.gn/x64.release/obj/v8_base/counters.o \
	deps/v8/out.gn/x64.release/obj/v8_base/cpu-profiler.o \
	deps/v8/out.gn/x64.release/obj/v8_base/cpu-x64.o \
	deps/v8/out.gn/x64.release/obj/v8_base/date.o \
	deps/v8/out.gn/x64.release/obj/v8_base/dateparser.o \
	deps/v8/out.gn/x64.release/obj/v8_base/dead-code-elimination.o \
	deps/v8/out.gn/x64.release/obj/v8_base/debug-coverage.o \
	deps/v8/out.gn/x64.release/obj/v8_base/debug-evaluate.o \
	deps/v8/out.gn/x64.release/obj/v8_base/debug-frames.o \
	deps/v8/out.gn/x64.release/obj/v8_base/debug-objects.o \
	deps/v8/out.gn/x64.release/obj/v8_base/debug-scope-iterator.o \
	deps/v8/out.gn/x64.release/obj/v8_base/debug-scopes.o \
	deps/v8/out.gn/x64.release/obj/v8_base/debug-stack-trace-iterator.o \
	deps/v8/out.gn/x64.release/obj/v8_base/debug-type-profile.o \
	deps/v8/out.gn/x64.release/obj/v8_base/debug-x64.o \
	deps/v8/out.gn/x64.release/obj/v8_base/debug.o \
	deps/v8/out.gn/x64.release/obj/v8_base/default-deserializer-allocator.o \
	deps/v8/out.gn/x64.release/obj/v8_base/default-serializer-allocator.o \
	deps/v8/out.gn/x64.release/obj/v8_base/deoptimize-reason.o \
	deps/v8/out.gn/x64.release/obj/v8_base/deoptimizer-x64.o \
	deps/v8/out.gn/x64.release/obj/v8_base/deoptimizer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/deserializer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/disasm-x64.o \
	deps/v8/out.gn/x64.release/obj/v8_base/disassembler.o \
	deps/v8/out.gn/x64.release/obj/v8_base/diy-fp.o \
	deps/v8/out.gn/x64.release/obj/v8_base/dtoa.o \
	deps/v8/out.gn/x64.release/obj/v8_base/effect-control-linearizer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/eh-frame-x64.o \
	deps/v8/out.gn/x64.release/obj/v8_base/eh-frame.o \
	deps/v8/out.gn/x64.release/obj/v8_base/elements-kind.o \
	deps/v8/out.gn/x64.release/obj/v8_base/elements.o \
	deps/v8/out.gn/x64.release/obj/v8_base/embedder-tracing.o \
	deps/v8/out.gn/x64.release/obj/v8_base/escape-analysis-reducer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/escape-analysis.o \
	deps/v8/out.gn/x64.release/obj/v8_base/execution.o \
	deps/v8/out.gn/x64.release/obj/v8_base/expression-scope-reparenter.o \
	deps/v8/out.gn/x64.release/obj/v8_base/external-reference-table.o \
	deps/v8/out.gn/x64.release/obj/v8_base/external-reference.o \
	deps/v8/out.gn/x64.release/obj/v8_base/externalize-string-extension.o \
	deps/v8/out.gn/x64.release/obj/v8_base/factory.o \
	deps/v8/out.gn/x64.release/obj/v8_base/fast-dtoa.o \
	deps/v8/out.gn/x64.release/obj/v8_base/feedback-vector.o \
	deps/v8/out.gn/x64.release/obj/v8_base/field-type.o \
	deps/v8/out.gn/x64.release/obj/v8_base/fixed-dtoa.o \
	deps/v8/out.gn/x64.release/obj/v8_base/flags.o \
	deps/v8/out.gn/x64.release/obj/v8_base/frame-constants-x64.o \
	deps/v8/out.gn/x64.release/obj/v8_base/frame-elider.o \
	deps/v8/out.gn/x64.release/obj/v8_base/frame-states.o \
	deps/v8/out.gn/x64.release/obj/v8_base/frame.o \
	deps/v8/out.gn/x64.release/obj/v8_base/frames.o \
	deps/v8/out.gn/x64.release/obj/v8_base/free-buffer-extension.o \
	deps/v8/out.gn/x64.release/obj/v8_base/func-name-inferrer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/function-body-decoder.o \
	deps/v8/out.gn/x64.release/obj/v8_base/futex-emulation.o \
	deps/v8/out.gn/x64.release/obj/v8_base/gap-resolver.o \
	deps/v8/out.gn/x64.release/obj/v8_base/gc-extension.o \
	deps/v8/out.gn/x64.release/obj/v8_base/gc-idle-time-handler.o \
	deps/v8/out.gn/x64.release/obj/v8_base/gc-tracer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/gdb-jit.o \
	deps/v8/out.gn/x64.release/obj/v8_base/global-handles.o \
	deps/v8/out.gn/x64.release/obj/v8_base/graph-assembler.o \
	deps/v8/out.gn/x64.release/obj/v8_base/graph-reducer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/graph-trimmer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/graph-visualizer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/graph.o \
	deps/v8/out.gn/x64.release/obj/v8_base/handler-configuration.o \
	deps/v8/out.gn/x64.release/obj/v8_base/handler-outside.o \
	deps/v8/out.gn/x64.release/obj/v8_base/handler-shared.o \
	deps/v8/out.gn/x64.release/obj/v8_base/handler-table-builder.o \
	deps/v8/out.gn/x64.release/obj/v8_base/handler-table.o \
	deps/v8/out.gn/x64.release/obj/v8_base/handles.o \
	deps/v8/out.gn/x64.release/obj/v8_base/heap-profiler.o \
	deps/v8/out.gn/x64.release/obj/v8_base/heap-snapshot-generator.o \
	deps/v8/out.gn/x64.release/obj/v8_base/heap.o \
	deps/v8/out.gn/x64.release/obj/v8_base/ic-stats.o \
	deps/v8/out.gn/x64.release/obj/v8_base/ic.o \
	deps/v8/out.gn/x64.release/obj/v8_base/icu_util.o \
	deps/v8/out.gn/x64.release/obj/v8_base/identity-map.o \
	deps/v8/out.gn/x64.release/obj/v8_base/ignition-statistics-extension.o \
	deps/v8/out.gn/x64.release/obj/v8_base/incremental-marking-job.o \
	deps/v8/out.gn/x64.release/obj/v8_base/incremental-marking.o \
	deps/v8/out.gn/x64.release/obj/v8_base/instruction-scheduler-x64.o \
	deps/v8/out.gn/x64.release/obj/v8_base/instruction-scheduler.o \
	deps/v8/out.gn/x64.release/obj/v8_base/instruction-selector-x64.o \
	deps/v8/out.gn/x64.release/obj/v8_base/instruction-selector.o \
	deps/v8/out.gn/x64.release/obj/v8_base/instruction-stream.o \
	deps/v8/out.gn/x64.release/obj/v8_base/instruction.o \
	deps/v8/out.gn/x64.release/obj/v8_base/int64-lowering.o \
	deps/v8/out.gn/x64.release/obj/v8_base/interface-descriptors-x64.o \
	deps/v8/out.gn/x64.release/obj/v8_base/interface-descriptors.o \
	deps/v8/out.gn/x64.release/obj/v8_base/interpreter-intrinsics.o \
	deps/v8/out.gn/x64.release/obj/v8_base/interpreter-irregexp.o \
	deps/v8/out.gn/x64.release/obj/v8_base/interpreter.o \
	deps/v8/out.gn/x64.release/obj/v8_base/intl-objects.o \
	deps/v8/out.gn/x64.release/obj/v8_base/intl.o \
	deps/v8/out.gn/x64.release/obj/v8_base/invalidated-slots.o \
	deps/v8/out.gn/x64.release/obj/v8_base/isolate.o \
	deps/v8/out.gn/x64.release/obj/v8_base/item-parallel-job.o \
	deps/v8/out.gn/x64.release/obj/v8_base/js-builtin-reducer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/js-call-reducer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/js-context-specialization.o \
	deps/v8/out.gn/x64.release/obj/v8_base/js-create-lowering.o \
	deps/v8/out.gn/x64.release/obj/v8_base/js-generic-lowering.o \
	deps/v8/out.gn/x64.release/obj/v8_base/js-graph.o \
	deps/v8/out.gn/x64.release/obj/v8_base/js-inlining-heuristic.o \
	deps/v8/out.gn/x64.release/obj/v8_base/js-inlining.o \
	deps/v8/out.gn/x64.release/obj/v8_base/js-intrinsic-lowering.o \
	deps/v8/out.gn/x64.release/obj/v8_base/js-native-context-specialization.o \
	deps/v8/out.gn/x64.release/obj/v8_base/js-operator.o \
	deps/v8/out.gn/x64.release/obj/v8_base/js-type-hint-lowering.o \
	deps/v8/out.gn/x64.release/obj/v8_base/js-typed-lowering.o \
	deps/v8/out.gn/x64.release/obj/v8_base/json-parser.o \
	deps/v8/out.gn/x64.release/obj/v8_base/json-stringifier.o \
	deps/v8/out.gn/x64.release/obj/v8_base/jsregexp.o \
	deps/v8/out.gn/x64.release/obj/v8_base/jump-threading.o \
	deps/v8/out.gn/x64.release/obj/v8_base/keys.o \
	deps/v8/out.gn/x64.release/obj/v8_base/layout-descriptor.o \
	deps/v8/out.gn/x64.release/obj/v8_base/liftoff-assembler.o \
	deps/v8/out.gn/x64.release/obj/v8_base/liftoff-compiler.o \
	deps/v8/out.gn/x64.release/obj/v8_base/linkage.o \
	deps/v8/out.gn/x64.release/obj/v8_base/literal-objects.o \
	deps/v8/out.gn/x64.release/obj/v8_base/live-range-separator.o \
	deps/v8/out.gn/x64.release/obj/v8_base/liveedit.o \
	deps/v8/out.gn/x64.release/obj/v8_base/load-elimination.o \
	deps/v8/out.gn/x64.release/obj/v8_base/local-decl-encoder.o \
	deps/v8/out.gn/x64.release/obj/v8_base/log-utils.o \
	deps/v8/out.gn/x64.release/obj/v8_base/log.o \
	deps/v8/out.gn/x64.release/obj/v8_base/lookup-cache.o \
	deps/v8/out.gn/x64.release/obj/v8_base/lookup.o \
	deps/v8/out.gn/x64.release/obj/v8_base/loop-analysis.o \
	deps/v8/out.gn/x64.release/obj/v8_base/loop-peeling.o \
	deps/v8/out.gn/x64.release/obj/v8_base/loop-variable-optimizer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/machine-graph-verifier.o \
	deps/v8/out.gn/x64.release/obj/v8_base/machine-operator-reducer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/machine-operator.o \
	deps/v8/out.gn/x64.release/obj/v8_base/machine-type.o \
	deps/v8/out.gn/x64.release/obj/v8_base/macro-assembler-x64.o \
	deps/v8/out.gn/x64.release/obj/v8_base/map-updater.o \
	deps/v8/out.gn/x64.release/obj/v8_base/mark-compact.o \
	deps/v8/out.gn/x64.release/obj/v8_base/marking.o \
	deps/v8/out.gn/x64.release/obj/v8_base/memory-optimizer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/memory-reducer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/memory-tracing.o \
	deps/v8/out.gn/x64.release/obj/v8_base/messages.o \
	deps/v8/out.gn/x64.release/obj/v8_base/module-compiler.o \
	deps/v8/out.gn/x64.release/obj/v8_base/module-decoder.o \
	deps/v8/out.gn/x64.release/obj/v8_base/module.o \
	deps/v8/out.gn/x64.release/obj/v8_base/modules.o \
	deps/v8/out.gn/x64.release/obj/v8_base/move-optimizer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/natives-common.o \
	deps/v8/out.gn/x64.release/obj/v8_base/node-cache.o \
	deps/v8/out.gn/x64.release/obj/v8_base/node-marker.o \
	deps/v8/out.gn/x64.release/obj/v8_base/node-matchers.o \
	deps/v8/out.gn/x64.release/obj/v8_base/node-properties.o \
	deps/v8/out.gn/x64.release/obj/v8_base/node.o \
	deps/v8/out.gn/x64.release/obj/v8_base/object-deserializer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/object-stats.o \
	deps/v8/out.gn/x64.release/obj/v8_base/objects-debug.o \
	deps/v8/out.gn/x64.release/obj/v8_base/objects-printer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/objects-visiting.o \
	deps/v8/out.gn/x64.release/obj/v8_base/objects.o \
	deps/v8/out.gn/x64.release/obj/v8_base/opcodes.o \
	deps/v8/out.gn/x64.release/obj/v8_base/operation-typer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/operator-properties.o \
	deps/v8/out.gn/x64.release/obj/v8_base/operator.o \
	deps/v8/out.gn/x64.release/obj/v8_base/optimizing-compile-dispatcher.o \
	deps/v8/out.gn/x64.release/obj/v8_base/osr.o \
	deps/v8/out.gn/x64.release/obj/v8_base/ostreams.o \
	deps/v8/out.gn/x64.release/obj/v8_base/parse-info.o \
	deps/v8/out.gn/x64.release/obj/v8_base/parser.o \
	deps/v8/out.gn/x64.release/obj/v8_base/parsing.o \
	deps/v8/out.gn/x64.release/obj/v8_base/partial-deserializer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/partial-serializer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/pattern-rewriter.o \
	deps/v8/out.gn/x64.release/obj/v8_base/pending-compilation-error-handler.o \
	deps/v8/out.gn/x64.release/obj/v8_base/perf-jit.o \
	deps/v8/out.gn/x64.release/obj/v8_base/pipeline-statistics.o \
	deps/v8/out.gn/x64.release/obj/v8_base/pipeline.o \
	deps/v8/out.gn/x64.release/obj/v8_base/preparse-data.o \
	deps/v8/out.gn/x64.release/obj/v8_base/preparsed-scope-data.o \
	deps/v8/out.gn/x64.release/obj/v8_base/preparser.o \
	deps/v8/out.gn/x64.release/obj/v8_base/prettyprinter.o \
	deps/v8/out.gn/x64.release/obj/v8_base/profile-generator.o \
	deps/v8/out.gn/x64.release/obj/v8_base/profiler-listener.o \
	deps/v8/out.gn/x64.release/obj/v8_base/property-access-builder.o \
	deps/v8/out.gn/x64.release/obj/v8_base/property-descriptor.o \
	deps/v8/out.gn/x64.release/obj/v8_base/property.o \
	deps/v8/out.gn/x64.release/obj/v8_base/raw-machine-assembler.o \
	deps/v8/out.gn/x64.release/obj/v8_base/redundancy-elimination.o \
	deps/v8/out.gn/x64.release/obj/v8_base/regexp-ast.o \
	deps/v8/out.gn/x64.release/obj/v8_base/regexp-macro-assembler-irregexp.o \
	deps/v8/out.gn/x64.release/obj/v8_base/regexp-macro-assembler-tracer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/regexp-macro-assembler-x64.o \
	deps/v8/out.gn/x64.release/obj/v8_base/regexp-macro-assembler.o \
	deps/v8/out.gn/x64.release/obj/v8_base/regexp-parser.o \
	deps/v8/out.gn/x64.release/obj/v8_base/regexp-stack.o \
	deps/v8/out.gn/x64.release/obj/v8_base/regexp-utils.o \
	deps/v8/out.gn/x64.release/obj/v8_base/register-allocator-verifier.o \
	deps/v8/out.gn/x64.release/obj/v8_base/register-allocator.o \
	deps/v8/out.gn/x64.release/obj/v8_base/register-configuration.o \
	deps/v8/out.gn/x64.release/obj/v8_base/representation-change.o \
	deps/v8/out.gn/x64.release/obj/v8_base/rewriter.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-array.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-atomics.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-bigint.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-classes.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-collections.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-compiler.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-date.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-debug.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-error.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-forin.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-function.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-futex.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-generator.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-internal.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-interpreter.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-intl.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-literals.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-liveedit.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-maths.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-module.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-numbers.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-object.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-operators.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-profiler.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-promise.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-proxy.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-regexp.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-scopes.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-strings.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-symbol.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-test.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-typedarray.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime-wasm.o \
	deps/v8/out.gn/x64.release/obj/v8_base/runtime.o \
	deps/v8/out.gn/x64.release/obj/v8_base/safepoint-table.o \
	deps/v8/out.gn/x64.release/obj/v8_base/sampling-heap-profiler.o \
	deps/v8/out.gn/x64.release/obj/v8_base/scanner-character-streams.o \
	deps/v8/out.gn/x64.release/obj/v8_base/scanner.o \
	deps/v8/out.gn/x64.release/obj/v8_base/scavenge-job.o \
	deps/v8/out.gn/x64.release/obj/v8_base/scavenger.o \
	deps/v8/out.gn/x64.release/obj/v8_base/schedule.o \
	deps/v8/out.gn/x64.release/obj/v8_base/scheduler.o \
	deps/v8/out.gn/x64.release/obj/v8_base/scope-info.o \
	deps/v8/out.gn/x64.release/obj/v8_base/scopes.o \
	deps/v8/out.gn/x64.release/obj/v8_base/select-lowering.o \
	deps/v8/out.gn/x64.release/obj/v8_base/serializer-common.o \
	deps/v8/out.gn/x64.release/obj/v8_base/serializer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/signature-map.o \
	deps/v8/out.gn/x64.release/obj/v8_base/simd-scalar-lowering.o \
	deps/v8/out.gn/x64.release/obj/v8_base/simplified-lowering.o \
	deps/v8/out.gn/x64.release/obj/v8_base/simplified-operator-reducer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/simplified-operator.o \
	deps/v8/out.gn/x64.release/obj/v8_base/simulator-base.o \
	deps/v8/out.gn/x64.release/obj/v8_base/simulator-x64.o \
	deps/v8/out.gn/x64.release/obj/v8_base/snapshot-common.o \
	deps/v8/out.gn/x64.release/obj/v8_base/snapshot-source-sink.o \
	deps/v8/out.gn/x64.release/obj/v8_base/source-position-table.o \
	deps/v8/out.gn/x64.release/obj/v8_base/source-position.o \
	deps/v8/out.gn/x64.release/obj/v8_base/spaces.o \
	deps/v8/out.gn/x64.release/obj/v8_base/startup-data-util.o \
	deps/v8/out.gn/x64.release/obj/v8_base/startup-deserializer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/startup-serializer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/state-values-utils.o \
	deps/v8/out.gn/x64.release/obj/v8_base/statistics-extension.o \
	deps/v8/out.gn/x64.release/obj/v8_base/store-buffer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/store-store-elimination.o \
	deps/v8/out.gn/x64.release/obj/v8_base/streaming-decoder.o \
	deps/v8/out.gn/x64.release/obj/v8_base/stress-marking-observer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/stress-scavenge-observer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/string-builder.o \
	deps/v8/out.gn/x64.release/obj/v8_base/string-case.o \
	deps/v8/out.gn/x64.release/obj/v8_base/string-stream.o \
	deps/v8/out.gn/x64.release/obj/v8_base/strings-storage.o \
	deps/v8/out.gn/x64.release/obj/v8_base/strtod.o \
	deps/v8/out.gn/x64.release/obj/v8_base/stub-cache.o \
	deps/v8/out.gn/x64.release/obj/v8_base/sweeper.o \
	deps/v8/out.gn/x64.release/obj/v8_base/switch-logic.o \
	deps/v8/out.gn/x64.release/obj/v8_base/template-objects.o \
	deps/v8/out.gn/x64.release/obj/v8_base/tick-sample.o \
	deps/v8/out.gn/x64.release/obj/v8_base/token.o \
	deps/v8/out.gn/x64.release/obj/v8_base/trace-event.o \
	deps/v8/out.gn/x64.release/obj/v8_base/traced-value.o \
	deps/v8/out.gn/x64.release/obj/v8_base/tracing-category-observer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/tracing-cpu-profiler.o \
	deps/v8/out.gn/x64.release/obj/v8_base/transitions.o \
	deps/v8/out.gn/x64.release/obj/v8_base/trigger-failure-extension.o \
	deps/v8/out.gn/x64.release/obj/v8_base/type-cache.o \
	deps/v8/out.gn/x64.release/obj/v8_base/type-hints.o \
	deps/v8/out.gn/x64.release/obj/v8_base/typed-optimization.o \
	deps/v8/out.gn/x64.release/obj/v8_base/typer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/types.o \
	deps/v8/out.gn/x64.release/obj/v8_base/unicode-decoder.o \
	deps/v8/out.gn/x64.release/obj/v8_base/unicode.o \
	deps/v8/out.gn/x64.release/obj/v8_base/unoptimized-compile-job.o \
	deps/v8/out.gn/x64.release/obj/v8_base/unwinding-info-writer-x64.o \
	deps/v8/out.gn/x64.release/obj/v8_base/uri.o \
	deps/v8/out.gn/x64.release/obj/v8_base/utils.o \
	deps/v8/out.gn/x64.release/obj/v8_base/v8.o \
	deps/v8/out.gn/x64.release/obj/v8_base/v8threads.o \
	deps/v8/out.gn/x64.release/obj/v8_base/value-numbering-reducer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/value-serializer.o \
	deps/v8/out.gn/x64.release/obj/v8_base/variables.o \
	deps/v8/out.gn/x64.release/obj/v8_base/vector-slot-pair.o \
	deps/v8/out.gn/x64.release/obj/v8_base/verifier.o \
	deps/v8/out.gn/x64.release/obj/v8_base/version.o \
	deps/v8/out.gn/x64.release/obj/v8_base/visitors.o \
	deps/v8/out.gn/x64.release/obj/v8_base/wasm-code-manager.o \
	deps/v8/out.gn/x64.release/obj/v8_base/wasm-code-specialization.o \
	deps/v8/out.gn/x64.release/obj/v8_base/wasm-compiler.o \
	deps/v8/out.gn/x64.release/obj/v8_base/wasm-debug.o \
	deps/v8/out.gn/x64.release/obj/v8_base/wasm-engine.o \
	deps/v8/out.gn/x64.release/obj/v8_base/wasm-external-refs.o \
	deps/v8/out.gn/x64.release/obj/v8_base/wasm-interpreter.o \
	deps/v8/out.gn/x64.release/obj/v8_base/wasm-js.o \
	deps/v8/out.gn/x64.release/obj/v8_base/wasm-linkage.o \
	deps/v8/out.gn/x64.release/obj/v8_base/wasm-memory.o \
	deps/v8/out.gn/x64.release/obj/v8_base/wasm-module-builder.o \
	deps/v8/out.gn/x64.release/obj/v8_base/wasm-module.o \
	deps/v8/out.gn/x64.release/obj/v8_base/wasm-objects.o \
	deps/v8/out.gn/x64.release/obj/v8_base/wasm-opcodes.o \
	deps/v8/out.gn/x64.release/obj/v8_base/wasm-result.o \
	deps/v8/out.gn/x64.release/obj/v8_base/wasm-serialization.o \
	deps/v8/out.gn/x64.release/obj/v8_base/wasm-text.o \
	deps/v8/out.gn/x64.release/obj/v8_base/zone-segment.o \
	deps/v8/out.gn/x64.release/obj/v8_base/zone-stats.o \
	deps/v8/out.gn/x64.release/obj/v8_base/zone.o \
	deps/v8/out.gn/x64.release/obj/v8_init/setup-isolate-full.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/accessor-assembler.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/binary-op-assembler.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-arguments-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-array-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-async-function-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-async-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-async-generator-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-async-iterator-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-boolean-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-call-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-collections-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-console-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-constructor-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-conversion-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-date-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-debug-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-function-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-generator-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-global-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-handler-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-ic-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-internal-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-interpreter-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-intl-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-iterator-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-math-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-number-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-object-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-promise-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-proxy-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-reflect-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-regexp-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-sharedarraybuffer-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-string-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-symbol-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-typedarray-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-wasm-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/builtins-x64.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/growable-fixed-array-gen.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/interpreter-assembler.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/interpreter-generator.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/interpreter-intrinsics-generator.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/keyed-store-generic.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/setup-builtins-internal.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/setup-heap-internal.o \
	deps/v8/out.gn/x64.release/obj/v8_initializers/setup-interpreter-internal.o \
	deps/v8/out.gn/x64.release/obj/v8_libbase/bits.o \
	deps/v8/out.gn/x64.release/obj/v8_libbase/condition-variable.o \
	deps/v8/out.gn/x64.release/obj/v8_libbase/cpu.o \
	deps/v8/out.gn/x64.release/obj/v8_libbase/division-by-constant.o \
	deps/v8/out.gn/x64.release/obj/v8_libbase/file-utils.o \
	deps/v8/out.gn/x64.release/obj/v8_libbase/functional.o \
	deps/v8/out.gn/x64.release/obj/v8_libbase/ieee754.o \
	deps/v8/out.gn/x64.release/obj/v8_libbase/logging.o \
	deps/v8/out.gn/x64.release/obj/v8_libbase/mutex.o \
	deps/v8/out.gn/x64.release/obj/v8_libbase/once.o \
	deps/v8/out.gn/x64.release/obj/v8_libbase/page-allocator.o \
	deps/v8/out.gn/x64.release/obj/v8_libbase/platform-macos.o \
	deps/v8/out.gn/x64.release/obj/v8_libbase/platform-posix-time.o \
	deps/v8/out.gn/x64.release/obj/v8_libbase/platform-posix.o \
	deps/v8/out.gn/x64.release/obj/v8_libbase/random-number-generator.o \
	deps/v8/out.gn/x64.release/obj/v8_libbase/semaphore.o \
	deps/v8/out.gn/x64.release/obj/v8_libbase/stack_trace.o \
	deps/v8/out.gn/x64.release/obj/v8_libbase/stack_trace_posix.o \
	deps/v8/out.gn/x64.release/obj/v8_libbase/sys-info.o \
	deps/v8/out.gn/x64.release/obj/v8_libbase/time.o \
	deps/v8/out.gn/x64.release/obj/v8_libplatform/default-background-task-runner.o \
	deps/v8/out.gn/x64.release/obj/v8_libplatform/default-foreground-task-runner.o \
	deps/v8/out.gn/x64.release/obj/v8_libplatform/default-platform.o \
	deps/v8/out.gn/x64.release/obj/v8_libplatform/task-queue.o \
	deps/v8/out.gn/x64.release/obj/v8_libplatform/trace-buffer.o \
	deps/v8/out.gn/x64.release/obj/v8_libplatform/trace-config.o \
	deps/v8/out.gn/x64.release/obj/v8_libplatform/trace-object.o \
	deps/v8/out.gn/x64.release/obj/v8_libplatform/trace-writer.o \
	deps/v8/out.gn/x64.release/obj/v8_libplatform/tracing-controller.o \
	deps/v8/out.gn/x64.release/obj/v8_libplatform/worker-thread.o \
	deps/v8/out.gn/x64.release/obj/v8_libsampler/sampler.o \
	deps/v8/out.gn/x64.release/obj/v8_nosnapshot/embedded-empty.o \
	deps/v8/out.gn/x64.release/obj/v8_nosnapshot/experimental-extras-libraries.o \
	deps/v8/out.gn/x64.release/obj/v8_nosnapshot/extras-libraries.o \
	deps/v8/out.gn/x64.release/obj/v8_nosnapshot/libraries.o \
	deps/v8/out.gn/x64.release/obj/v8_nosnapshot/snapshot-empty.o

all: dist/purr

re: clean all

dist/purr: src/purr.cc dist deps
	@${CXX} ${CXX_FLAGS} ${V8_ARCHIVES} src/purr.cc -o $@

dist:
	@mkdir dist

clean:
	@rm -rf dist

deps:
	@make -C deps all

.PHONY: deps
